import { createFileRoute, Link } from "@tanstack/react-router";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms & Conditions — LIBerico" },
      {
        name: "description",
        content: "Terms and conditions for using LIBerico.",
      },
    ],
  }),
  component: TermsPage,
});

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="mb-3 text-lg font-semibold text-foreground">{title}</h2>
      <div className="space-y-3 text-sm leading-relaxed text-foreground/80">{children}</div>
    </section>
  );
}

function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <div className="mx-auto max-w-2xl px-4 py-12">
        <Link to="/" className="mb-8 inline-block text-sm text-primary hover:underline">
          ← Back to home
        </Link>

        <h1 className="mb-2 font-serif text-3xl font-semibold text-ink">Terms & Conditions</h1>
        <p className="mb-10 text-xs text-foreground/40">Last updated: 10 May 2026</p>

        <Section title="About LIBerico">
          <p>
            LIBerico is an AI-assisted educational practice tool for students preparing for the
            International Baccalaureate (IB) Language A: Literature and Language B assessments.
            LIBerico is operated from Sweden.
          </p>
          <p>
            LIBerico is not affiliated with, endorsed by, or connected to the International
            Baccalaureate Organization (IBO). "International Baccalaureate" and "IB" are registered
            trademarks of the IBO. LIBerico does not guarantee any specific IB score or exam
            outcome.
          </p>
          <p>
            By creating an account or using LIBerico you agree to these Terms & Conditions and our{" "}
            <Link to="/privacy" className="text-primary hover:underline">
              Privacy Policy
            </Link>
            .
          </p>
        </Section>

        <Section title="Eligibility">
          <p>
            To use LIBerico you must meet the minimum age and consent requirements described in our{" "}
            <Link to="/privacy" className="text-primary hover:underline">
              Privacy Policy
            </Link>{" "}
            (at least 13 years old, or with parental/guardian consent where your country's law
            requires a higher age). If you are signing up on behalf of a minor, you confirm that you
            have the authority to do so.
          </p>
        </Section>

        <Section title="Account responsibility">
          <p>
            You are responsible for keeping your account credentials secure. Do not share your
            password. Provide accurate information when creating your account. Notify us immediately
            at{" "}
            <a href="mailto:epetterssonruiz@gmail.com" className="text-primary hover:underline">
              epetterssonruiz@gmail.com
            </a>{" "}
            if you believe your account has been compromised.
          </p>
        </Section>

        <Section title="Acceptable use">
          <p>You agree not to:</p>
          <ul className="ml-4 list-disc space-y-1">
            <li>Abuse, spam, or overload the service in ways that harm other users.</li>
            <li>
              Attempt to scrape, reverse-engineer, or extract AI model weights or system prompts.
            </li>
            <li>Attempt to access another user's account or data.</li>
            <li>Attempt to bypass or circumvent usage quotas.</li>
            <li>Upload content that is illegal, harmful, or violates third-party rights.</li>
            <li>Use the service for any purpose other than personal educational practice.</li>
          </ul>
        </Section>

        <Section title="Academic integrity">
          <p>
            LIBerico is a practice and learning tool. Feedback generated by LIBerico is intended to
            help you understand your work, identify areas for improvement, and revise your writing.
          </p>
          <p>
            <strong>
              You must not submit AI-generated text as your own work in any IB assessment or
              examination.
            </strong>{" "}
            Using LIBerico to produce text that you present as your own in an assessed context
            constitutes academic dishonesty and may violate your school's academic integrity policy
            and IB regulations.
          </p>
        </Section>

        <Section title="Your content">
          <p>
            You retain ownership of the texts and work you submit to LIBerico. By submitting
            content, you grant LIBerico a limited, non-exclusive licence to process that content
            solely to provide, secure, and improve the service. We do not claim ownership of your
            work and do not sell it to third parties.
          </p>
        </Section>

        <Section title="AI limitations">
          <p>
            Feedback generated by LIBerico is produced by AI models and may be incomplete,
            inaccurate, or inconsistent. It does not constitute official IB marking or a guarantee
            of any specific score. You should always review AI feedback critically and discuss it
            with a qualified teacher or examiner where possible.
          </p>
        </Section>

        <Section title="Copyright">
          <p>
            You must only submit texts that you are permitted to use for educational analysis (for
            example, works your school has licensed or texts in the public domain). LIBerico does
            not reproduce or distribute protected works. Brief quotations used for the purpose of
            literary commentary fall within fair use / fair dealing principles in most
            jurisdictions, but you are responsible for ensuring your use is lawful.
          </p>
        </Section>

        <Section title="Sessions and bookings">
          <p>
            If you use the tutoring booking feature, scheduling data (availability, session times,
            email addresses used for Google Calendar and Meet invites) is handled as described in
            our{" "}
            <Link to="/privacy" className="text-primary hover:underline">
              Privacy Policy
            </Link>
            . Session arrangements are between you and the teacher; LIBerico facilitates the booking
            but is not a party to the tutoring relationship.
          </p>
        </Section>

        <Section title="Payments">
          <p>
            LIBerico does not currently offer any paid subscriptions or charge for access. If paid
            tiers are introduced in the future, these Terms will be updated before any payment is
            processed, and you will be given clear notice of pricing and billing terms before being
            charged.
          </p>
        </Section>

        <Section title="Suspension and termination">
          <p>
            LIBerico reserves the right to suspend or terminate accounts that violate these Terms,
            misuse the service, or engage in harmful behaviour, with or without notice depending on
            severity.
          </p>
          <p>
            You may delete your account at any time from{" "}
            <Link to="/cuenta" className="text-primary hover:underline">
              Account settings
            </Link>
            . Deletion permanently removes your profile and evaluation history from our systems.
          </p>
        </Section>

        <Section title="Changes to these Terms">
          <p>
            We may update these Terms from time to time. For material changes we will notify you by
            email or via an in-app notice before the changes take effect. Continued use of the
            service after that date constitutes acceptance of the updated Terms.
          </p>
          <p>
            Questions? Contact us at{" "}
            <a href="mailto:epetterssonruiz@gmail.com" className="text-primary hover:underline">
              epetterssonruiz@gmail.com
            </a>
            .
          </p>
        </Section>

        <p className="mt-10 text-xs text-foreground/40">
          See also our{" "}
          <Link to="/privacy" className="underline hover:text-foreground/70">
            Privacy Policy
          </Link>{" "}
          and{" "}
          <Link to="/cookies" className="underline hover:text-foreground/70">
            Cookie Policy
          </Link>
          .
        </p>
      </div>
    </div>
  );
}
