/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeoriaRouteImport } from './routes/teoria'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MiPlanRouteImport } from './routes/mi-plan'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as EjerciciosRouteImport } from './routes/ejercicios'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as IndexRouteImport } from './routes/index'

const TeoriaRoute = TeoriaRouteImport.update({
  id: '/teoria',
  path: '/teoria',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MiPlanRoute = MiPlanRouteImport.update({
  id: '/mi-plan',
  path: '/mi-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const EjerciciosRoute = EjerciciosRouteImport.update({
  id: '/ejercicios',
  path: '/ejercicios',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/ejercicios': typeof EjerciciosRoute
  '/historial': typeof HistorialRoute
  '/login': typeof LoginRoute
  '/mi-plan': typeof MiPlanRoute
  '/onboarding': typeof OnboardingRoute
  '/teoria': typeof TeoriaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/ejercicios': typeof EjerciciosRoute
  '/historial': typeof HistorialRoute
  '/login': typeof LoginRoute
  '/mi-plan': typeof MiPlanRoute
  '/onboarding': typeof OnboardingRoute
  '/teoria': typeof TeoriaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/ejercicios': typeof EjerciciosRoute
  '/historial': typeof HistorialRoute
  '/login': typeof LoginRoute
  '/mi-plan': typeof MiPlanRoute
  '/onboarding': typeof OnboardingRoute
  '/teoria': typeof TeoriaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biblioteca'
    | '/ejercicios'
    | '/historial'
    | '/login'
    | '/mi-plan'
    | '/onboarding'
    | '/teoria'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biblioteca'
    | '/ejercicios'
    | '/historial'
    | '/login'
    | '/mi-plan'
    | '/onboarding'
    | '/teoria'
  id:
    | '__root__'
    | '/'
    | '/biblioteca'
    | '/ejercicios'
    | '/historial'
    | '/login'
    | '/mi-plan'
    | '/onboarding'
    | '/teoria'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliotecaRoute: typeof BibliotecaRoute
  EjerciciosRoute: typeof EjerciciosRoute
  HistorialRoute: typeof HistorialRoute
  LoginRoute: typeof LoginRoute
  MiPlanRoute: typeof MiPlanRoute
  OnboardingRoute: typeof OnboardingRoute
  TeoriaRoute: typeof TeoriaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teoria': {
      id: '/teoria'
      path: '/teoria'
      fullPath: '/teoria'
      preLoaderRoute: typeof TeoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-plan': {
      id: '/mi-plan'
      path: '/mi-plan'
      fullPath: '/mi-plan'
      preLoaderRoute: typeof MiPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial': {
      id: '/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof HistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ejercicios': {
      id: '/ejercicios'
      path: '/ejercicios'
      fullPath: '/ejercicios'
      preLoaderRoute: typeof EjerciciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliotecaRoute: BibliotecaRoute,
  EjerciciosRoute: EjerciciosRoute,
  HistorialRoute: HistorialRoute,
  LoginRoute: LoginRoute,
  MiPlanRoute: MiPlanRoute,
  OnboardingRoute: OnboardingRoute,
  TeoriaRoute: TeoriaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
